### ISSUE TITLE
Please give some examples of grid generation

### ISSUE THREAD

**Issue by verglas** [zofe/rapyd-framework#8]
Unable to use ordery by:

```
$dg->add('{{ adsense.deduction }}元/{% if adsense.deduction_type==2 %}展示{% else %}点击{% endif %}',"扣费方式", true);
```

Links with Chinese characters

Unable to deal with special fields:

```
Digital library field values:1,2,3
Shown in the template into A/B/C
```

Unable to use with parameters of router:

```
$dg->add('<a  data-url="'.$this->app->urlFor('Alliance_Save_Expenditure').'/{{ adsense.id }}" data-title="请输入新余额" data-name="expenditure" class="btn btn-primary">{{ adsense.expenditure }}</a>',"余额");
```

Please help me, thank you

**Comment by zofe** [comment]
a computed field, can't be ordered if it's computed in column declaration. 

however it's simple to move your logic from twig to your query, using DB::raw("select *, concat(deduction, IF(deduction_type=2, '展示', '点击')) from ....").

About char-encoding:
Charset is by default utf8 (for DB connection and Twig configuration)  so if your DB/tables/fields are utf8 it should be correct. If not, check if some filter like convert-encoding  can solve the problem: http://twig.sensiolabs.org/doc/filters/convert_encoding.html

About url/router, try to comment the last method ( urlFor ) in  /src/Rapyd/Application.php to use the Slim one.

**Comment by verglas** [comment]
I use the environment to the Rapyd\Widgets\DataGrid
How to modify the access data in the DataGrid let it show in the template?

rapyd-framework  cannot use raw with grid

```
    public function setSource($source, $as=null)
    {

        $this->source = $source;
        if (is_null($as) && is_a($source, "\Illuminate\Database\Eloquent\Builder")){

            $reflection = new \ReflectionClass(get_class($source->getModel()));
            $this->row_as = strtolower($reflection->getShortName());

        } elseif (is_null($as) && is_a($source, "\Illuminate\Database\Eloquent\Model")){
            $reflection = new \ReflectionClass(get_class($source));
            $this->row_as = strtolower($reflection->getShortName());
        }
        return $this;
    }
```

rapyd-framework  cannot use DB class:

```
$data = $this->app->db->raw("select *, IF(deduction_type=2, '展示', '点击') as deduction_type_show from adsense")
//object Illuminate\Database\Query\Expression

$dg = $this->grid->createBuilder();
$dg->setSource($data);
```

```
Missing argument 1 for Rapyd\Widgets\DataGrid\Column::setRow_as()
```

UrlFor I know the second parameter for the parameter array, but I do not use in the datagrid.
I now is this:

```
$dg->add('<a  data-url="'.$this->app->urlFor('Alliance_Save_Expenditure').'/{{ adsense.id }}" data-title="请输入新余额" data-name="expenditure" class="btn btn-primary">{{ adsense.expenditure }}</a>',"余额");
```

urlFor

```
Fatal error: Call to undefined method Slim\Views\Twig::getLang() in src\Rapyd\Application.php on line 348
```

I put Application.php Comment urlFor function in PHP.

thanks

**Comment by verglas** [comment]
I need the datagrid and dataset document, thank you.

**Comment by zofe** [comment]
You're right about raw query, It's not enabled (for both, DS DG).
please consider to make a Entity, and use Eloquent "Accessors" to change fields output.
Or ti make a computed array and pass it to DS. If DG can't work with arrays  just fork and fix it.
http://laravel.com/docs/eloquent#accessors-and-mutators

About  custom template for DataGrid the default one is in
\Rapyd\Views\DataGrid.twig copy and paste it in your  \App\Views,  make your changes.

About documentation ad fixes on rapyd-framework  this is not my priority, again I encourage you to "fork" and make you changes, fixes or check if another framework that fits your needs.

I'm working only rapyd-laravel for now, and even there I expect  the same flow:
1) fork  
2) open issues 
3) pull request (if you fix before me).

Sorry
